numbers = [5,4,3,2,3,3,3,1]
numbers.append(15)
print(numbers)
numbers.insert(0,25)
print(numbers)
numbers.remove(5)
print(numbers)
print(numbers)
numbers.pop()
print(numbers)
print(numbers.index(2))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers2 = numbers.copy()
print(numbers2)
numbers.append(7)
print(numbers)
print(numbers2)
numbers2.append(30)
print(numbers2)
print(numbers)
print(numbers.count(3 ))
print (50 in numbers)
#print(numbers.index(50))
print(numbers)
numbers.clear()
print(numbers)
